version: 1.0.0.{build}
pull_requests:
  do_not_increment_build_number: true
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: 'branch={branch},commit=$(APPVEYOR_REPO_COMMIT)'
nuget:
  disable_publish_on_pr: true
build_script:
- ps: ./build.ps1
artifacts:
- path: _artifacts\**\*.nupkg
  name: nupkg
deploy:
- provider: NuGet
  api_key:
    secure: RQoX6Hri/INRDmlamwUZnd2rE0p1YR737lJXOlzAK8e1tv/yuDuU+aoqHYsP7pgQ
  on:
    branch: master