version: 1.0.{build}
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{branch}-${APPVEYOR_REPO_COMMIT}'
build:
  verbosity: minimal
build_script:
- ps: ./build.ps1
artifacts:
- path: _artifacts\**\*.nupkg
  name: nupkg
deploy:
- provider: NuGet
  api_key:
    secure: fHWbfn3Ml9/5SRqusX4diFC/gYWQkQ1gvXUZjICjRsdjNgUfSMrBqym7Nyq6TISD
  on:
    branch: master